traiterJson({
"trait":2,
"numDiag":2,
"notes":"Une position à nombre de pièces réduit. Ici, pour gagner, les rouges jouent 4->0.",
"fen":"tdtUDU42 r",
"cols":[
	{"nb":3, "couleur":1},
	{"nb":2, "couleur":1},
	{"nb":3, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":2, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":0, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0}
]
});
